### ISSUE TITLE
Check non alignée

### ISSUE THREAD

**Issue by newick** [flusio/Flus#709]
![image](https://github.com/user-attachments/assets/57a5835a-cd20-4511-bba8-3e07a53f9e85)
![image](https://github.com/user-attachments/assets/454f8481-b6c6-459a-a640-0333030a8254)

Sur Firefox, quand je spécifie la thématique de mon dossier, la coche n'est pas alignée.

**Comment by marienfressinaud** [comment]
Merci ! Ce sera corrigé dans la prochaine version (j’espère demain !)
