### ISSUE TITLE
Ignorer la casse dans le champ de recherche de « Mes liens », pour les #tags

### ISSUE THREAD

**Issue by alainmi11** [flusio/Flus#717]
Bonjour,

Je découvre Flus depuis peu, et c'est juste top !
Bravo pour cet outil.

J'ai testé la fonctionnalité de l'ajout de tags dans les commentaires d'un lien, dans une collection et je remarque que quand on fait une recherche dans « _Mes liens_ » sur un tag qu'on a déjà créé, pour pouvoir le retrouver il faut le saisir dans le champ de recherche exactement comme on l'a créé, avec les mêmes lettres en majuscule ou minuscule et si on se trompe, la recherche ne renvoie rien.
Par exemple, si le tag créé était #MonHashtag et qu'on fait la recherche en écrivant #monhashtag, on n'a aucun résultat.
C'est pas très pratique.

D'où ma demande : 
➜ Est-il possible de modifier ça et de faire en sorte d'**ignorer la casse dans le champ de recherche**, au moins pour les #tags ?

**Comment by marienfressinaud** [comment]
Le correctif est développé, il devrait être disponible demain sur flus.fr. Merci pour la suggestion !

**Comment by alainmi11** [comment]
Merci !!!
🙏

**Comment by marienfressinaud** [comment]
Et c’est en place :)

**Comment by alainmi11** [comment]
Et je confirme que ça marche, nickel.
Encore merci.
